# Generated by Django 5.2.2 on 2025-11-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size_label')},
        ),
    ]
