# Generated by Django 5.2.2 on 2025-11-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cardtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpaymentmethod',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
