# Generated by Django 5.2.2 on 2025-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_assigned_to_support_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret_word',
            field=models.CharField(blank=True, help_text='Используется для восстановления пароля и подтверждения важных действий', max_length=255, null=True, verbose_name='Секретное слово'),
        ),
    ]
