# Generated by Django 5.2.2 on 2025-11-16 17:18

from django.db import migrations
from decimal import Decimal


def fix_negative_balances(apps, schema_editor):
    """Исправляет отрицательные балансы карт, устанавливая их в 0"""
    SavedPaymentMethod = apps.get_model('main', 'SavedPaymentMethod')
    
    # Находим все карты с отрицательным балансом
    cards_with_negative_balance = SavedPaymentMethod.objects.filter(balance__lt=0)
    
    for card in cards_with_negative_balance:
        # Устанавливаем баланс в 0, так как баланс карты не может быть отрицательным
        card.balance = Decimal('0.00')
        card.save(update_fields=['balance'])


def reverse_fix(apps, schema_editor):
    """Обратная операция - не требуется, так как мы исправляем некорректные данные"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_secret_word_to_userprofile'),
    ]

    operations = [
        migrations.RunPython(fix_negative_balances, reverse_fix),
    ]
