# Generated by Django 5.2.2 on 2025-11-16 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_fix_products_with_zero_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('backup_name', models.CharField(max_length=255, verbose_name='Название бэкапа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('schedule', models.CharField(choices=[('now', 'Прямо сейчас'), ('weekly', 'Каждую неделю'), ('monthly', 'Раз в месяц'), ('yearly', 'Раз в год')], default='now', max_length=20, verbose_name='Расписание')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Автоматический бэкап')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'Бэкап базы данных',
                'verbose_name_plural': 'Бэкапы базы данных',
                'ordering': ['-created_at'],
            },
        ),
    ]
