# Generated by Django 5.2.2 on 2025-11-16 18:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_database_backup_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс')),
                ('tax_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Резерв на налоги (13%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Счет организации',
                'verbose_name_plural': 'Счет организации',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма налога (13%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, verbose_name='Налог на прибыль (%)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма товаров'),
        ),
        migrations.CreateModel(
            name='OrganizationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('order_payment', 'Поступление от заказа'), ('order_refund', 'Возврат по отмене заказа'), ('tax_payment', 'Оплата налога'), ('withdrawal', 'Вывод на карту админа')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_reserve_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_reserve_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_transactions', to='main.order')),
                ('organization_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.organizationaccount')),
            ],
            options={
                'verbose_name': 'Транзакция счета организации',
                'verbose_name_plural': 'Транзакции счета организации',
                'ordering': ['-created_at'],
            },
        ),
    ]
