# Generated by Django 5.2.2 on 2025-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_organizationaccount_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='org_account_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccount',
            constraint=models.CheckConstraint(condition=models.Q(('tax_reserve__gte', 0)), name='org_account_tax_reserve_non_negative'),
        ),
    ]
